### ISSUE TITLE
Set password : File not found

### ISSUE THREAD

**Issue by Boyquotes** [bludnic/opentrader#57]
Hi,

When I use this command after installation, I have an error:
```
opentrader set-password **MYPASSWORD**
```
Error:
Password file not found!

I have installed with bun i -g and use node v20.15.1

**Comment by bludnic** [comment]
I wouldn't recommend using Bun for now, as there is no guarantee that the app will behave the same as in a Node.js environment. Do you encounter the same issue when installing via NPM? @Boyquotes

**Comment by Boyquotes** [comment]
Effectively, with npm all works fine.
