### ISSUE TITLE
how to use ccxt with proxy?

### ISSUE THREAD

**Issue by touhoufan2024** [bludnic/opentrader#63]
i can't access okx's info

![image](https://github.com/user-attachments/assets/e82be41b-5c59-496d-8e58-64b182c4fd33)

i need proxy; this is ccxt doc

https://docs.ccxt.com/#/?id=proxy

**Comment by bludnic** [comment]
Here is the CCXT [connector](https://github.com/bludnic/opentrader/blob/dev/packages/exchanges/src/exchanges/ccxt/exchange.ts#L75). You can try adding a proxy there, but you'll have to compile the project from [source code](https://github.com/bludnic/opentrader/blob/dev/CONTRIBUTING.md) by yourself.

**Comment by bludnic** [comment]
It would probably be easier and a more universal solution to set up a proxy at the OS level, just to avoid dealing with the source code. @touhoufan2024

**Comment by bludnic** [comment]
CCXT Docs: https://docs.ccxt.com/#/?id=proxy

This also may help:

- https://github.com/ccxt/ccxt/issues/20686
- https://github.com/ccxt/ccxt/issues/4259

@touhoufan2024 please close the issue if it's already resolved for you
